language: bash

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.0-rc3

before_install:
  - docker-compose --version
  - docker pull koalaman/shellcheck:v0.4.6
  - docker pull lukasmartinelli/hadolint:latest
  - curl -L https://github.com/docker/compose/releases/download/1.23.0-rc3/docker-compose-`uname -s`-`uname -m` -o docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - docker-compose --version
  - wget https://ftpmirror.gnu.org/parallel/parallel-20181022.tar.bz2
  - bzip2 -dc parallel-20181022.tar.bz2 | tar xvf -
  - (cd parallel-20181022 && ./configure && make && sudo make install && cd ../ && rm -rf parallel-20181022*)
  - bash ./tools/kubectl/install.sh
  - bash ./tools/kubectl/configure.sh
  - bash ./tools/helm/install.sh

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && DO_PUBLISH='y' TAG="$TRAVIS_COMMIT" bash ./tools/travis/build.sh
  - bash ./tools/travis/lint.sh

script:
  - bash ./tools/travis/analyse.sh
  - bash ./tools/travis/unit-tests.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./tools/travis/deploy/production.sh
    on:
      branch: master