{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}-redis
    helm.sh/chart: {{ include "helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: port-6379
      protocol: TCP
      name: port-6379
  selector:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}-redis
{{- end -}}