{{- if .Values.cron.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: cron
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}-cron
    helm.sh/chart: {{ include "helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-cron
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.cron.service.type }}
  ports:
    - port: {{ .Values.cron.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}-cron
    app.kubernetes.io/instance: {{ .Release.Name }}-cron
  {{- end -}}