{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}-web
    helm.sh/chart: {{ include "helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}-web
  {{- end -}}